from manim import *
import numpy as np
import json

# Harmonious design palette (matching previous chapters for style consistency)
BG_COLOR = "#0f172a"      # Sleek slate-900 background
RUST_ORANGE = "#ea580c"   # Vibrant Rust Orange
CYAN = "#06b6d4"          # Accent Cyan
PURPLE = "#8b5cf6"        # Accent Purple/Violet
WHITE = "#f1f5f9"         # Off-white text
GRAY = "#64748b"          # Slate-500 for secondary elements and borders
GREEN = "#10b981"         # Emerald-500 for positives
RED = "#ef4444"           # Red-500 for challenges/errors
YELLOW = "#f59e0b"        # Yellow-500 for warnings/info
LIGHT_BG = "#1e293b"      # slate-800 for card backgrounds
TERM_BG = "#090d16"       # Dark deep blue for terminal windows

def create_terminal_window(width, height, title_text):
    window = RoundedRectangle(corner_radius=0.15, width=width, height=height, color=GRAY, fill_color=TERM_BG, fill_opacity=0.95, stroke_width=2)
    # Header line separating title bar
    header_bar = Line(
        start=[-width/2, height/2 - 0.45, 0], 
        end=[width/2, height/2 - 0.45, 0], 
        color=GRAY, 
        stroke_width=2
    )
    # Window control dots (Red, Yellow, Green)
    red_dot = Circle(radius=0.07, color=RED, fill_opacity=1, stroke_width=0).move_to([-width/2 + 0.25, height/2 - 0.22, 0])
    yellow_dot = Circle(radius=0.07, color=YELLOW, fill_opacity=1, stroke_width=0).move_to([-width/2 + 0.45, height/2 - 0.22, 0])
    green_dot = Circle(radius=0.07, color=GREEN, fill_opacity=1, stroke_width=0).move_to([-width/2 + 0.65, height/2 - 0.22, 0])
    # Window Title
    title = Text(title_text, font_size=11, color=GRAY).move_to([0, height/2 - 0.22, 0])
    
    return VGroup(window, header_bar, red_dot, yellow_dot, green_dot, title)

class RustCompoundDatatypesVideo(Scene):
    def construct(self):
        self.camera.background_color = BG_COLOR

        # Load durations generated by TTS script
        try:
            with open("audio/durations_ch8.json", "r") as f:
                durations = json.load(f)
        except Exception:
            # Fallback placeholder durations if file not written yet
            durations = {
                "ch8_1_intro": 21.0,
                "ch8_2_array_intro": 22.0,
                "ch8_3_array_syntax": 27.0,
                "ch8_4_array_functions": 20.0,
                "ch8_5_array_indexing": 26.0,
                "ch8_6_tuple_intro": 24.0,
                "ch8_7_tuple_access": 18.0,
                "ch8_8_tuple_destructuring": 20.0,
                "ch8_9_tuple_debug_outro": 27.0
            }

        # ==========================================
        # SECTION 1: INTRO
        # ==========================================
        dur_1 = durations["ch8_1_intro"]
        self.add_sound("audio/ch8_1_intro.wav")

        # 0s - 3s: Title
        title = Text("Rust für Anfänger", font_size=46, color=RUST_ORANGE, weight=BOLD)
        subtitle = Text("Kapitel 8: Arrays & Tupel", font_size=28, color=CYAN)
        title_group = VGroup(title, subtitle).arrange(DOWN, buff=0.4)
        
        self.play(FadeIn(title_group, shift=UP), run_time=1.0)
        self.wait(2.0) # total 3.0s

        # 3s - 4.5s: Move Title to Top
        title_small = Text("Kapitel 8: Zusammengesetzte Datentypen", font_size=26, color=RUST_ORANGE, weight=BOLD).to_edge(UP, buff=0.5)
        self.play(Transform(title_group, title_small), run_time=1.5) # total 4.5s
        self.wait(0.5) # total 5.0s

        # 5s - 12s: Show Cards
        card1 = RoundedRectangle(corner_radius=0.12, width=5.4, height=2.4, color=CYAN, fill_color=LIGHT_BG, fill_opacity=0.8, stroke_width=2).move_to([-3.0, 0.4, 0])
        card1_title = Text("Array (Feld)", font_size=16, color=CYAN, weight=BOLD).next_to(card1.get_top(), DOWN, buff=0.3)
        card1_desc = Text("Homogen: Nur ein Typ\nFeste Größe: Unveränderlich", font_size=12, color=WHITE).next_to(card1_title, DOWN, buff=0.2)
        card1_group = VGroup(card1, card1_title, card1_desc)

        card2 = RoundedRectangle(corner_radius=0.12, width=5.4, height=2.4, color=PURPLE, fill_color=LIGHT_BG, fill_opacity=0.8, stroke_width=2).move_to([3.0, 0.4, 0])
        card2_title = Text("Tupel", font_size=16, color=PURPLE, weight=BOLD).next_to(card2.get_top(), DOWN, buff=0.3)
        card2_desc = Text("Heterogen: Mix erlaubt\nFeste Größe: Unveränderlich", font_size=12, color=WHITE).next_to(card2_title, DOWN, buff=0.2)
        card2_group = VGroup(card2, card2_title, card2_desc)

        self.play(FadeIn(card1_group, shift=RIGHT), FadeIn(card2_group, shift=LEFT), run_time=1.5) # total 6.5s
        self.wait(5.5) # total 12.0s

        # 12s - end: Show summary message at bottom
        summary_txt = Text("Bündeln mehrere Werte in einer einzigen Variable.", font_size=14, color=WHITE).move_to([0, -1.8, 0])
        self.play(FadeIn(summary_txt, shift=UP), run_time=1.0) # total 13.0s
        self.wait(max(0.1, dur_1 - 13.0 - 1.0))
        self.play(FadeOut(card1_group), FadeOut(card2_group), FadeOut(summary_txt), FadeOut(title_group), run_time=1.0)


        # ==========================================
        # SECTION 2: WHAT IS AN ARRAY?
        # ==========================================
        dur_2 = durations["ch8_2_array_intro"]
        self.add_sound("audio/ch8_2_array_intro.wav")

        sec2_title = Text("1. Was ist ein Array?", font_size=30, color=RUST_ORANGE, weight=BOLD).to_edge(UP, buff=0.5)
        self.play(FadeIn(sec2_title, shift=UP), run_time=1.0) # total 1.0s
        self.wait(1.0) # total 2.0s

        # Draw a visual box with 6 elements (slots)
        array_boxes = VGroup(*[
            Square(side_length=0.9, color=CYAN, fill_color=LIGHT_BG, fill_opacity=0.9, stroke_width=2.5)
            for _ in range(6)
        ]).arrange(RIGHT, buff=0.15).move_to([0, 1.2, 0])
        
        vals = [4, 8, 15, 16, 23, 42]
        array_texts = VGroup(*[
            Text(str(val), font_size=18, color=WHITE).move_to(box.get_center())
            for val, box in zip(vals, array_boxes)
        ])
        array_visual = VGroup(array_boxes, array_texts)

        self.play(Create(array_boxes), Write(array_texts), run_time=1.5) # total 3.5s
        self.wait(4.5) # total 8.0s

        # Show 3 cards detailing the properties
        card_w, card_h = 3.6, 2.2
        prop_card1 = RoundedRectangle(corner_radius=0.1, width=card_w, height=card_h, color=CYAN, fill_color=LIGHT_BG, fill_opacity=0.8, stroke_width=2.0).move_to([-4.0, -1.2, 0])
        pc1_title = Text("Homogen", font_size=14, color=CYAN, weight=BOLD).next_to(prop_card1.get_top(), DOWN, buff=0.2)
        pc1_desc = Text("Alle Elemente vom\nselben Typ (z.B. i32)", font_size=11, color=WHITE).next_to(pc1_title, DOWN, buff=0.15)
        pc1_group = VGroup(prop_card1, pc1_title, pc1_desc)

        prop_card2 = RoundedRectangle(corner_radius=0.1, width=card_w, height=card_h, color=PURPLE, fill_color=LIGHT_BG, fill_opacity=0.8, stroke_width=2.0).move_to([0, -1.2, 0])
        pc2_title = Text("Feste Größe", font_size=14, color=PURPLE, weight=BOLD).next_to(prop_card2.get_top(), DOWN, buff=0.2)
        pc2_desc = Text("Anzahl der Fächer ist\nvon Anfang an fest", font_size=11, color=WHITE).next_to(pc2_title, DOWN, buff=0.15)
        pc2_group = VGroup(prop_card2, pc2_title, pc2_desc)

        prop_card3 = RoundedRectangle(corner_radius=0.1, width=card_w, height=card_h, color=GREEN, fill_color=LIGHT_BG, fill_opacity=0.8, stroke_width=2.0).move_to([4.0, -1.2, 0])
        pc3_title = Text("Geordnet", font_size=14, color=GREEN, weight=BOLD).next_to(prop_card3.get_top(), DOWN, buff=0.2)
        pc3_desc = Text("Elemente in einer\nfesten Reihenfolge", font_size=11, color=WHITE).next_to(pc3_title, DOWN, buff=0.15)
        pc3_group = VGroup(prop_card3, pc3_title, pc3_desc)

        self.play(
            FadeIn(pc1_group, shift=UP),
            FadeIn(pc2_group, shift=UP),
            FadeIn(pc3_group, shift=UP),
            run_time=2.0
        ) # total 10.0s

        self.wait(max(0.1, dur_2 - 10.0 - 1.0))
        self.play(
            FadeOut(array_visual),
            FadeOut(pc1_group), FadeOut(pc2_group), FadeOut(pc3_group),
            FadeOut(sec2_title),
            run_time=1.0
        )


        # ==========================================
        # SECTION 3: ARRAY SYNTAX
        # ==========================================
        dur_3 = durations["ch8_3_array_syntax"]
        self.add_sound("audio/ch8_3_array_syntax.wav")

        sec3_title = Text("2. Syntax in Rust", font_size=30, color=RUST_ORANGE, weight=BOLD).to_edge(UP, buff=0.5)
        self.play(FadeIn(sec3_title, shift=UP), run_time=1.0) # total 1.0s
        self.wait(1.0) # total 2.0s

        # Code editor window
        editor = create_terminal_window(11.0, 3.4, "src/main.rs").move_to([0, 0.4, 0])
        code_text = Paragraph(
            "// Typinferenz (wird automatisch als [i32; 6] erkannt):",
            "let numbers = [4, 8, 15, 16, 23, 42];",
            "",
            "// Explizite Typschreibweise: [Typ; Anzahl]",
            "let numbers: [i32; 6] = [4, 8, 15, 16, 23, 42];",
            font_size=13, line_spacing=0.6, color=WHITE
        ).move_to(editor.get_center()).shift(LEFT * 1.3 + UP * 0.1)

        self.play(FadeIn(editor), FadeIn(code_text), run_time=1.5) # total 3.5s
        self.wait(6.5) # total 10.0s

        # Highlight explicit type definition
        highlight_rect = Rectangle(width=2.1, height=0.45, color=CYAN, stroke_width=2.5).move_to([-1.57, -0.22, 0])
        label_type = Text("[Typ; Anzahl]", font_size=12, color=CYAN, weight=BOLD).next_to(highlight_rect, DOWN, buff=0.25)
        
        self.play(Create(highlight_rect), FadeIn(label_type), run_time=1.5) # total 11.5s
        self.wait(5.5) # total 17.0s

        # Warning card below
        warn_card = RoundedRectangle(corner_radius=0.1, width=11.0, height=1.4, color=RED, fill_color=LIGHT_BG, fill_opacity=0.9, stroke_width=2.0).move_to([0, -2.4, 0])
        warn_title = Text("⚠ Wichtig:", font_size=14, color=RED, weight=BOLD).next_to(warn_card.get_top(), DOWN, buff=0.15).align_to(warn_card, LEFT).shift(RIGHT * 0.5)
        warn_desc = Text("Die angegebene Anzahl im Typ [i32; 6] MUSS exakt mit der Anzahl der\nElemente in der Klammer übereinstimmen. Sonst streikt der Compiler!", font_size=11, color=WHITE).next_to(warn_title, DOWN, buff=0.1).align_to(warn_title, LEFT)
        warn_group = VGroup(warn_card, warn_title, warn_desc)

        self.play(FadeIn(warn_group, shift=UP), run_time=1.5) # total 18.5s
        self.wait(max(0.1, dur_3 - 18.5 - 1.0))
        self.play(FadeOut(editor), FadeOut(code_text), FadeOut(highlight_rect), FadeOut(label_type), FadeOut(warn_group), FadeOut(sec3_title), run_time=1.0)


        # ==========================================
        # SECTION 4: FUNCTIONS & SPECIAL CASES
        # ==========================================
        dur_4 = durations["ch8_4_array_functions"]
        self.add_sound("audio/ch8_4_array_functions.wav")

        sec4_title = Text("3. Funktionen & Sonderfälle", font_size=30, color=RUST_ORANGE, weight=BOLD).to_edge(UP, buff=0.5)
        self.play(FadeIn(sec4_title, shift=UP), run_time=1.0) # total 1.0s
        self.wait(1.0) # total 2.0s

        editor4 = create_terminal_window(11.0, 3.4, "src/main.rs").move_to([0, 0.4, 0])
        code_text4 = Paragraph(
            "// Länge abfragen:",
            "let length = numbers.len(); // Ergibt 6",
            "",
            "// Leere Arrays (nur mit explizitem Typ erlaubt):",
            "let empty_array: [f64; 0] = []; // Gültig",
            font_size=13, line_spacing=0.6, color=WHITE
        ).move_to(editor4.get_center()).shift(LEFT * 1.5 + UP * 0.1)

        self.play(FadeIn(editor4), FadeIn(code_text4), run_time=1.5) # total 3.5s
        self.wait(6.5) # total 10.0s

        # Info card below
        info_card = RoundedRectangle(corner_radius=0.15, width=11.0, height=1.4, color=CYAN, fill_color=LIGHT_BG, fill_opacity=0.9, stroke_width=2.0).move_to([0, -2.4, 0])
        info_desc = Text("Da der Compiler leere Arrays nicht automatisch zuordnen kann,\nmuss der Typ und die Länge 0 (z. B. [f64; 0]) explizit deklariert werden.", font_size=11, color=WHITE).move_to(info_card.get_center())
        info_group = VGroup(info_card, info_desc)

        self.play(FadeIn(info_group, shift=UP), run_time=1.5) # total 11.5s
        self.wait(max(0.1, dur_4 - 11.5 - 1.0))
        self.play(FadeOut(editor4), FadeOut(code_text4), FadeOut(info_group), FadeOut(sec4_title), run_time=1.0)


        # ==========================================
        # SECTION 5: INDEXING & MUTATION
        # ==========================================
        dur_5 = durations["ch8_5_array_indexing"]
        self.add_sound("audio/ch8_5_array_indexing.wav")

        sec5_title = Text("4. Indexierung & Werte überschreiben", font_size=30, color=RUST_ORANGE, weight=BOLD).to_edge(UP, buff=0.5)
        self.play(FadeIn(sec5_title, shift=UP), run_time=1.0) # total 1.0s
        self.wait(1.0) # total 2.0s

        # Seasons Array Visual
        seasons_boxes = VGroup(*[
            Square(side_length=1.1, color=CYAN, fill_color=LIGHT_BG, fill_opacity=0.9, stroke_width=2.5)
            for _ in range(4)
        ]).arrange(RIGHT, buff=0.3).move_to([0, 1.3, 0])
        
        seasons_vals = ["Frühling", "Sommer", "Fall", "Winter"]
        seasons_texts = VGroup(*[
            Text(val, font_size=13, color=WHITE).move_to(box.get_center())
            for val, box in zip(seasons_vals, seasons_boxes)
        ])
        
        seasons_indices = VGroup(*[
            Text(f"Index {i}", font_size=11, color=GRAY).next_to(box, DOWN, buff=0.15)
            for i, box in enumerate(seasons_boxes)
        ])
        seasons_visual = VGroup(seasons_boxes, seasons_texts, seasons_indices)

        self.play(Create(seasons_boxes), Write(seasons_texts), FadeIn(seasons_indices), run_time=1.5) # total 3.5s
        self.wait(4.5) # total 8.0s

        # Show code editor below
        editor5 = create_terminal_window(11.0, 2.2, "src/main.rs").move_to([0, -1.3, 0])
        code_text5 = Paragraph(
            "let mut seasons = [\"Frühling\", \"Sommer\", \"Fall\", \"Winter\"];",
            "seasons[2] = \"Herbst\"; // Ersetzt \"Fall\" durch \"Herbst\"",
            font_size=13, line_spacing=0.5, color=WHITE
        ).move_to(editor5.get_center()).shift(LEFT * 1.5 + UP * 0.1)

        self.play(FadeIn(editor5), FadeIn(code_text5), run_time=1.5) # total 9.5s
        self.wait(2.5) # total 12.0s

        # Animate Mutation
        new_val_text = Text("Herbst", font_size=13, color=GREEN).move_to(seasons_boxes[2].get_center())
        box_highlight = seasons_boxes[2].copy().set_color(GREEN).set_stroke_width(3.5)

        self.play(
            Transform(seasons_texts[2], new_val_text),
            Create(box_highlight),
            run_time=1.5
        ) # total 13.5s
        self.wait(1.5) # total 15.0s

        # Show Vector preview badge
        vec_badge = RoundedRectangle(corner_radius=0.1, width=8.5, height=0.6, color=YELLOW, fill_color=YELLOW, fill_opacity=0.15, stroke_width=2).move_to([0, -2.8, 0])
        vec_text = Text("💡 Vorschau: Für dynamisch wachsende Listen nutzt man Vektoren.", font_size=11, color=YELLOW, weight=BOLD).move_to(vec_badge.get_center())
        vec_group = VGroup(vec_badge, vec_text)

        self.play(FadeIn(vec_group, shift=UP), run_time=1.5) # total 16.5s
        self.wait(max(0.1, dur_5 - 16.5 - 1.0))
        self.play(FadeOut(seasons_visual), FadeOut(editor5), FadeOut(code_text5), FadeOut(box_highlight), FadeOut(vec_group), FadeOut(sec5_title), run_time=1.0)


        # ==========================================
        # SECTION 6: TUPLE INTRO
        # ==========================================
        dur_6 = durations["ch8_6_tuple_intro"]
        self.add_sound("audio/ch8_6_tuple_intro.wav")

        sec6_title = Text("5. Das Tupel: Der flexible Mix-Container", font_size=28, color=RUST_ORANGE, weight=BOLD).to_edge(UP, buff=0.5)
        self.play(FadeIn(sec6_title, shift=UP), run_time=1.0) # total 1.0s
        self.wait(1.0) # total 2.0s

        # Comparison boxes
        compare_array = RoundedRectangle(corner_radius=0.12, width=5.4, height=1.8, color=CYAN, fill_color=LIGHT_BG, fill_opacity=0.8, stroke_width=2.0).move_to([-3.0, 1.8, 0])
        ca_title = Text("Array", font_size=14, color=CYAN, weight=BOLD).next_to(compare_array.get_top(), DOWN, buff=0.2)
        ca_desc = Text("Homogen (z. B. nur i32)", font_size=11, color=WHITE).next_to(ca_title, DOWN, buff=0.15)
        ca_group = VGroup(compare_array, ca_title, ca_desc)

        compare_tuple = RoundedRectangle(corner_radius=0.12, width=5.4, height=1.8, color=PURPLE, fill_color=LIGHT_BG, fill_opacity=0.8, stroke_width=2.0).move_to([3.0, 1.8, 0])
        ct_title = Text("Tupel", font_size=14, color=PURPLE, weight=BOLD).next_to(compare_tuple.get_top(), DOWN, buff=0.2)
        ct_desc = Text("Heterogen (Mix von Typen erlaubt)", font_size=11, color=WHITE).next_to(ct_title, DOWN, buff=0.15)
        ct_group = VGroup(compare_tuple, ct_title, ct_desc)

        self.play(FadeIn(ca_group, shift=RIGHT), FadeIn(ct_group, shift=LEFT), run_time=1.5) # total 3.5s
        self.wait(4.5) # total 8.0s

        # Visual Tuple container with elements of different types/colors
        tuple_container = RoundedRectangle(corner_radius=0.15, width=7.5, height=1.4, color=PURPLE, fill_color=LIGHT_BG, fill_opacity=0.9, stroke_width=2.5).move_to([0, -0.6, 0])
        bracket_l = Text("(", font_size=42, color=PURPLE, weight=BOLD).next_to(tuple_container, LEFT, buff=0.2)
        bracket_r = Text(")", font_size=42, color=PURPLE, weight=BOLD).next_to(tuple_container, RIGHT, buff=0.2)
        
        elem1 = Text('"Molly"', font_size=15, color=CYAN).move_to(tuple_container.get_center()).shift(LEFT * 2.2)
        elem2 = Text('32', font_size=15, color=GREEN).move_to(tuple_container.get_center())
        elem3 = Text('"Marketing"', font_size=15, color=CYAN).move_to(tuple_container.get_center()).shift(RIGHT * 2.2)
        
        commas = VGroup(
            Text(",", font_size=15, color=WHITE).next_to(elem1, RIGHT, buff=0.7),
            Text(",", font_size=15, color=WHITE).next_to(elem2, RIGHT, buff=0.8)
        )
        tuple_visual = VGroup(tuple_container, bracket_l, bracket_r, elem1, elem2, elem3, commas)

        self.play(FadeIn(tuple_visual, shift=UP), run_time=1.5) # total 9.5s
        self.wait(2.5) # total 12.0s

        # Show matching code statement below
        code_tuple = Text("let employee = (\"Molly\", 32, \"Marketing\");", font_size=15, color=WHITE).move_to([0, -2.2, 0])
        self.play(Write(code_tuple), run_time=1.5) # total 13.5s

        self.wait(max(0.1, dur_6 - 13.5 - 1.0))
        self.play(FadeOut(ca_group), FadeOut(ct_group), FadeOut(tuple_visual), FadeOut(code_tuple), FadeOut(sec6_title), run_time=1.0)


        # ==========================================
        # SECTION 7: TUPLE ACCESS
        # ==========================================
        dur_7 = durations["ch8_7_tuple_access"]
        self.add_sound("audio/ch8_7_tuple_access.wav")

        sec7_title = Text("6. Zugriff über die Punkt-Notation", font_size=30, color=RUST_ORANGE, weight=BOLD).to_edge(UP, buff=0.5)
        self.play(FadeIn(sec7_title, shift=UP), run_time=1.0) # total 1.0s
        self.wait(1.0) # total 2.0s

        # Draw the tuple visually at the top
        tuple_container = RoundedRectangle(corner_radius=0.15, width=7.5, height=1.1, color=PURPLE, fill_color=LIGHT_BG, fill_opacity=0.9, stroke_width=2.5).move_to([0, 1.5, 0])
        bracket_l = Text("(", font_size=32, color=PURPLE, weight=BOLD).next_to(tuple_container, LEFT, buff=0.2)
        bracket_r = Text(")", font_size=32, color=PURPLE, weight=BOLD).next_to(tuple_container, RIGHT, buff=0.2)
        elem1 = Text('"Molly"', font_size=14, color=CYAN).move_to(tuple_container.get_center()).shift(LEFT * 2.2)
        elem2 = Text('32', font_size=14, color=GREEN).move_to(tuple_container.get_center())
        elem3 = Text('"Marketing"', font_size=14, color=CYAN).move_to(tuple_container.get_center()).shift(RIGHT * 2.2)
        commas = VGroup(
            Text(",", font_size=14, color=WHITE).next_to(elem1, RIGHT, buff=0.7),
            Text(",", font_size=14, color=WHITE).next_to(elem2, RIGHT, buff=0.8)
        )
        tuple_visual = VGroup(tuple_container, bracket_l, bracket_r, elem1, elem2, elem3, commas)

        # Draw indices
        idx1 = Text("Index .0", font_size=11, color=GRAY).next_to(elem1, DOWN, buff=0.25)
        idx2 = Text("Index .1", font_size=11, color=GRAY).next_to(elem2, DOWN, buff=0.25)
        idx3 = Text("Index .2", font_size=11, color=GRAY).next_to(elem3, DOWN, buff=0.25)
        indices = VGroup(idx1, idx2, idx3)

        self.play(FadeIn(tuple_visual), FadeIn(indices), run_time=1.5) # total 3.5s
        self.wait(2.5) # total 6.0s

        # Editor window showing code
        editor7 = create_terminal_window(11.0, 2.6, "src/main.rs").move_to([0, -1.5, 0])
        code_text7 = Paragraph(
            "let name = employee.0;       // \"Molly\"",
            "let age = employee.1;        // 32",
            "let department = employee.2; // \"Marketing\"",
            font_size=13, line_spacing=0.5, color=WHITE
        ).move_to(editor7.get_center()).shift(LEFT * 1.5 + UP * 0.1)

        self.play(FadeIn(editor7), FadeIn(code_text7), run_time=1.5) # total 7.5s
        self.wait(1.5) # total 9.0s

        # Draw arrows from indices to code values
        arrow1 = Arrow(start=idx1.get_bottom(), end=[-3.5, -0.8, 0], color=CYAN, stroke_width=2, tip_length=0.15)
        arrow2 = Arrow(start=idx2.get_bottom(), end=[-3.5, -1.1, 0], color=GREEN, stroke_width=2, tip_length=0.15)
        arrow3 = Arrow(start=idx3.get_bottom(), end=[-3.5, -1.4, 0], color=CYAN, stroke_width=2, tip_length=0.15)
        arrows = VGroup(arrow1, arrow2, arrow3)

        self.play(Create(arrows), run_time=1.5) # total 10.5s

        self.wait(max(0.1, dur_7 - 10.5 - 1.0))
        self.play(FadeOut(tuple_visual), FadeOut(indices), FadeOut(editor7), FadeOut(code_text7), FadeOut(arrows), FadeOut(sec7_title), run_time=1.0)


        # ==========================================
        # SECTION 8: TUPLE DESTRUCTURING
        # ==========================================
        dur_8 = durations["ch8_8_tuple_destructuring"]
        self.add_sound("audio/ch8_8_tuple_destructuring.wav")

        sec8_title = Text("7. Destrukturieren (Musterabgleich)", font_size=30, color=RUST_ORANGE, weight=BOLD).to_edge(UP, buff=0.5)
        self.play(FadeIn(sec8_title, shift=UP), run_time=1.0) # total 1.0s
        self.wait(1.0) # total 2.0s

        # Code editor
        editor8 = create_terminal_window(11.0, 3.2, "src/main.rs").move_to([0, 0.4, 0])
        code_text8 = Paragraph(
            "// Zerlegt das Tupel direkt in einzelne Variablen:",
            "let (name, age, department) = employee;",
            "",
            "// Jetzt kannst du sie einzeln nutzen:",
            "println!(\"Name: {}, Alter: {}\", name, age);",
            font_size=13, line_spacing=0.6, color=WHITE
        ).move_to(editor8.get_center()).shift(LEFT * 1.5 + UP * 0.1)

        self.play(FadeIn(editor8), FadeIn(code_text8), run_time=1.5) # total 3.5s
        self.wait(4.5) # total 8.0s

        # Destructuring visual card below
        destruct_card = RoundedRectangle(corner_radius=0.12, width=11.0, height=1.6, color=GREEN, fill_color=LIGHT_BG, fill_opacity=0.9, stroke_width=2.5).move_to([0, -2.4, 0])
        dc_desc = Paragraph(
            "Rust entpackt das Tupel automatisch von links nach rechts:",
            "  • name = \"Molly\"   |   • age = 32   |   • department = \"Marketing\"",
            font_size=12, line_spacing=0.5, color=WHITE
        ).move_to(destruct_card.get_center())
        dc_group = VGroup(destruct_card, dc_desc)

        self.play(FadeIn(dc_group, shift=UP), run_time=1.5) # total 9.5s
        self.wait(max(0.1, dur_8 - 9.5 - 1.0))
        self.play(FadeOut(editor8), FadeOut(code_text8), FadeOut(dc_group), FadeOut(sec8_title), run_time=1.0)


        # ==========================================
        # SECTION 9: DEBUG MODE & EXAMPLE
        # ==========================================
        dur_9 = durations["ch8_9_tuple_debug_outro"]
        self.add_sound("audio/ch8_9_tuple_debug_outro.wav")

        sec9_title = Text("8. Debuggen & Komplettes Beispiel", font_size=30, color=RUST_ORANGE, weight=BOLD).to_edge(UP, buff=0.5)
        self.play(FadeIn(sec9_title, shift=UP), run_time=1.0) # total 1.0s
        self.wait(1.0) # total 2.0s

        # Show compare printing
        print_err = RoundedRectangle(corner_radius=0.1, width=11.0, height=0.7, color=RED, fill_color=LIGHT_BG, fill_opacity=0.9, stroke_width=2.0).move_to([0, 1.8, 0])
        pe_text = Text("✘ let's print normally: println!(\"{}\", person);  --> Führt zu Compilerfehler!", font_size=11, color=RED, weight=BOLD).move_to(print_err.get_center())
        print_err_group = VGroup(print_err, pe_text)

        print_ok = RoundedRectangle(corner_radius=0.1, width=11.0, height=0.7, color=GREEN, fill_color=LIGHT_BG, fill_opacity=0.9, stroke_width=2.0).move_to([0, 0.9, 0])
        po_text = Text("✔ Debug-Format verwenden: println!(\"{:?}\", person); --> Funktioniert!", font_size=11, color=GREEN, weight=BOLD).move_to(print_ok.get_center())
        print_ok_group = VGroup(print_ok, po_text)

        self.play(FadeIn(print_err_group, shift=DOWN), run_time=1.0) # total 3.0s
        self.wait(1.0) # total 4.0s
        self.play(FadeIn(print_ok_group, shift=DOWN), run_time=1.0) # total 5.0s
        self.wait(3.0) # total 8.0s

        # Code window on left, Terminal on right
        editor9 = create_terminal_window(6.8, 3.6, "src/main.rs").move_to([-3.4, -1.8, 0])
        code_text9 = Paragraph(
            "fn main() {",
            "    let person = (\"Alex\", 28, true);",
            "    let alter = person.1;",
            "    let (name, age, ist_aktiv) = person;",
            "    println!(\"{:?}\", person);",
            "}",
            font_size=10, line_spacing=0.4, color=WHITE
        ).move_to(editor9.get_center()).shift(LEFT * 0.7 + UP * 0.1)

        terminal = create_terminal_window(5.4, 2.2, "Terminal").move_to([3.4, -1.8, 0])
        term_text = Paragraph(
            "$ cargo run",
            "(\"Alex\", 28, true)",
            font_size=10, line_spacing=0.4, color=GREEN
        ).move_to(terminal.get_center()).shift(LEFT * 1.0 + UP * 0.1)

        self.play(
            FadeOut(print_err_group),
            FadeOut(print_ok_group),
            FadeIn(editor9, shift=UP),
            FadeIn(code_text9),
            run_time=1.5
        ) # total 9.5s
        self.wait(2.5) # total 12.0s

        self.play(
            FadeIn(terminal, shift=LEFT),
            FadeIn(term_text),
            run_time=1.5
        ) # total 13.5s

        # Wait until near the end
        outro_time = 18.0
        self.wait(max(0.1, outro_time - 13.5)) # total 18.0s

        # Transition to final outro
        outro_text = Text("Nächstes Kapitel:\nFunktionen in Rust", font_size=32, color=CYAN, weight=BOLD).move_to([0, -0.2, 0])
        self.play(
            FadeOut(editor9),
            FadeOut(code_text9),
            FadeOut(terminal),
            FadeOut(term_text),
            FadeIn(outro_text, shift=UP),
            run_time=1.5
        ) # total 19.5s

        self.wait(max(0.1, dur_9 - 19.5 - 1.0))
        self.play(FadeOut(outro_text), FadeOut(sec9_title), run_time=1.0)
