[book]
authors = ["Thorsten"]
language = "de"
src = "src"
title = "Rust-Videokurs für Anfänger"

[rust]
edition = "2021"

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
